# Generated by Django 4.2.4 on 2023-10-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='core_comment',
        ),
    ]
